apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pd8k6dbwh-nodejs
  janus-idp.io/tekton: pd8k6dbwh-nodejs
  backstage.io/kubernetes-id: pd8k6dbwh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pd8k6dbwh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
