apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pd8k6dbwh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pd8k6dbwh-nodejs 
  name: pd8k6dbwh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pd8k6dbwh-nodejs 
